services:
  mongo:
    image: mongo
    container_name: mongodb
    environment:
      - MONGO_INITDB_DATABASE=github
    volumes:
      - ./data:/data/db
    restart: on-failure

  backend:
    build: .
    container_name: backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/github  
    volumes:
      - ./app:/app
